PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX depiction: <http://purl.obolibrary.org/obo/foaf_depiction>
SELECT DISTINCT ?term ?label ?depictedby ?prop ?comment
WHERE {
 {
   ?term rdfs:label ?label .
   ?term depiction: ?depictedby .
  ?annotation owl:annotatedSource ?term ;
                    owl:annotatedProperty depiction: ;
                    rdfs:comment ?comment .

 }
 FILTER(isIRI(?term) && regex(str(?term), "PLANA_")) .
 FILTER(regex(str(?depictedby), "png")) .
}
