PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?term ?depictedBy ?imageComment
WHERE {
  { ?s1 ?p1 ?term .
  ?term rdfs:label ?label .
  ?term obo:foaf_depicted_by ?depictedBy.
  ?annotation owl:annotatedSource ?term ;
                    owl:annotatedTarget ?depictedBy ;
                    rdfs:comment ?imageComment .

 FILTER(isIRI(?term) && regex(str(?term), "PLANA_")).
  FILTER (!isBlank(?imageComment)).
  }

}


